### PR TITLE
Animation to Beepbox

### PR DESCRIPTION
**Pull request by Agzam4**
### When the playhaed touches a note, it turns white and smoothly returns to its default color:
image

***
### This can be turned off/on by the button:
image

***

You can find the changes in the code by pressing ctrl+F, and inserting `#AGZAM4`

I'm changed only this files:
```
\website\3_0\beepbox_offline.html <-- Only JS been change
\website\3_0\beepbox_editor.js
```

_Edit: This is also made for beepbox 4.0.1 but don't not added it to this pull request, because this repository don't have `\website\4_0_1\` folder_

### CODE REVIEW

**Comment by Agzam4** [comment]
I'm added this effect to player of Beepbox 4.0.1

**Comment by Moonlacer** [comment]
This looks sick, I would highly recommend this to be added as an option

**Comment by johnnesky** [comment]
I don't think I can accept this pull request as-is, for several reasons. Most importantly, it makes changes to generated files (.js) instead of source files (.ts) and thus will get replaced the next time I compile from source.  Also, I think I could make the animation significantly more efficient, right now it looks like it's adding new svg elements to the DOM every frame without cleaning up the old ones. But yes, this would be a neat option to have, I'll keep it in mind, and thanks for the demo!

**Comment by Agzam4** [comment]
> I don't think I can accept this pull request as-is, for several reasons. Most importantly, it makes changes to generated files (.js) instead of source files (.ts) and thus will get replaced the next time I compile from source. Also, I think I could make the animation significantly more efficient, right now it looks like it's adding new svg elements to the DOM every frame without cleaning up the old ones. But yes, this would be a neat option to have, I'll keep it in mind, and thanks for the demo!

I knew you wouldn't accept the extraction request, but just in case I'll leave a link to the version with animation  :)
[click](https://agzam4.github.io/Scratch-Beepbox/beepbox/#)

PS: maybe I should try to do it using `canvas`


Maybe it will come in handy:
```
function makeColorBrighter(hex, k) { 
        var R = 0;
        var G = 0;
        var B = 0;
        if(hex.length == 3) {
            R = parseInt(hex.substring(0,1),16);
            G = parseInt(hex.substring(1,2),16);
            B = parseInt(hex.substring(2,3),16);
        }else {
            R = parseInt(hex.substring(0,2),16);
            G = parseInt(hex.substring(2,4),16);
            B = parseInt(hex.substring(4,6),16);
        }
        if(k < 0) k = 0;
        if(k > 1) k = 1;
        // Color of light is rgb(iR iG iB)
        let iR = 255;//119;
        let iG = 255;//68;
        let iB = 255;
        R = (R-iR)*k+iR;
        G = (G-iG)*k+iG;
        B = (B-iB)*k+iB;

        return "rgb("+R+","+G+","+B+")";
    }
```

```
if (this._pattern != null && this._doc.animation) {
                        for (const note of this._pattern.notes) {
                            for (let i = 0; i < note.pitches.length; i++) {
                                const pitch = note.pitches[i];
                                let notePath = SVG.path();
                                let pathPrimaryFill = "";
                                let pathSecondaryFill = "";

                                let agzam4Let = (this._playheadX * this._editorWidth - 2);
                                    if((this._partWidth * note.start + 2) < agzam4Let) {
                                    var rootStyles = getComputedStyle(document.querySelector(':root'));
                                    var hex1 = rootStyles.getPropertyValue(
                                            ColorConfig.getChannelColor(this._doc.song, this._doc.channel).primaryNote.replace("var(", "").replace(")", "")
                                        ).replaceAll("#", "").replaceAll(" ", "");
                                    var hex2 = rootStyles.getPropertyValue(
                                            ColorConfig.getChannelColor(this._doc.song, this._doc.channel).secondaryNote.replace("var(", "").replace(")", "")
                                        ).replaceAll("#", "").replaceAll(" ", "");
                                    let k = (agzam4Let - (this._partWidth * note.start + 2))*0.01;
                                    pathPrimaryFill = makeColorBrighter(hex1, k);
                                    pathSecondaryFill = makeColorBrighter(hex2, k);
                                }else {
                                    pathPrimaryFill= ColorConfig.getChannelColor(this._doc.song, this._doc.channel).primaryNote;
                                    pathSecondaryFill= ColorConfig.getChannelColor(this._doc.song, this._doc.channel).secondaryNote;
                                }
    
                                notePath.setAttribute("fill", pathSecondaryFill);
                                notePath.setAttribute("pointer-events", "none");


                                this._drawNote(notePath, pitch, note.start, note.pins, this._pitchHeight / 2 + 1, false, this._octaveOffset);
                                this._svgNoteContainer.appendChild(notePath);
                                notePath = SVG.path();
                            
                                notePath.setAttribute("fill", pathPrimaryFill);

                                notePath.setAttribute("pointer-events", "none");
                                this._drawNote(notePath, pitch, note.start, note.pins, this._pitchHeight / 2 + 1, true, this._octaveOffset);
                                this._svgNoteContainer.appendChild(notePath);
                            }
                        }
```

**Pull request closed without merging**
