### PR TITLE
Midi device input

### PR DESCRIPTION
**Pull request by zOadT**
Hey!

This PR allows to use a connected MIDI device to play sounds similar to the on screen piano keys, but also allows to play chords instead of just single tones.

For now I just injected depencies through the constructor. If there is any kind of event system or similar to resolve these direct dependencies I will happily adapt that.
The classes were structured without much knowledge about the global domain model, so I would also appreciate feedback if I should restructure them.
I'm thinking about letting `LiveInput` handle the calls of `this._doc.synth.maintainLiveInput` using an interval. Would that be ok?

One thing to keep in mind: Midi events don't seem to allow the creation of AudioContexts (at least not in Chrome). Therefore the user has to play a sound through some kind of pointer event before being able to hear the midi sounds. So maybe it would be a good idea to let the user manually activate a midi device? That would maybe also be useful if the user uses multiple music softwares and doesn't want Beepbox to recognize a device.

This feature is currently only tested in Chrome with the AKAI MPK Mini (The only midi device I own). Firefox doesn't support the Web Midi API yet, but it seems Firefox 99 will support it. So we should also test it in FF before merging.

### CODE REVIEW

**Comment by johnnesky** [comment]
Hi! This is pretty cool, thanks for figuring this out!

I have some suggestions:
1. If navigator.requestMIDIAccess is null (e.g. in Firefox) then MidiInput.ts line 29 is an error because you can't bind null. I suggest testing if navigator.requestMIDIAccess is null **before** doing the binding... but I think you don't need binding anyway, see the next suggestion.
2. You can tell the TypeScript compiler that navigator should have a property called requestMIDIAccess by putting this at the top of MidiInput.ts:
    ```
    declare global {
    	interface Navigator {
    		requestMIDIAccess: any;
    	}
    }
    ```
    That should allow you to simplify the (navigator as any).requestMIDIAccess thing into just navigator.requestMIDIAccess, in which case you don't really need to do any binding and might as well just refer to it directly when you need it.
3. You also can add this to the top of MidiInput.ts:
    ```
    import {MidiEventType} from "./Midi";
    ```
    Then MidiEventType can replace your MIDI_EVENT enum. Instead of eventType.toString(16)[0], I recommend using bitwise math to isolate the bits on the left, like this: eventType & 0xF0, and you can compare that to MidiEventType.noteOn and MidiEventType.noteOff. 
4. The MIDI standard defines a note-on event with a velocity of zero as being equivalent to a note-off event. The velocity is the third element of the midi event, so you can access it like so:
    ```
    let [eventType, key, velocity] = event.data;
    ```
    And if velocity is zero in the note-on event, you should call removeNote. This is necessary for compatibility with many MIDI devices.

I think the general structure of the classes and dependencies is fine, you did a great job working within BeepBox's code, thanks!

You suggested calling maintainLiveInput on a regular interval... Hm. I deliberately added the maintainLiveInput feature because I wanted to shut off the synth if the user stops using BeepBox, even if they leave the tab open, in order to avoid wasting CPU time when they're looking at something else. I only call maintainLiveInput in response to user input events, and if enough time goes by without any such user input events, the synth will shut off, but as soon as a new user input event occurs, it'll call maintainLiveInput which starts it up again. I think this is still working more or less as intended in your version as long as the user clicks somewhere first, although if a user holds down a note for a long time without releasing it or doing anything else, it'll eventually shut off anyway. The delay is currently 10 seconds.

As a legal technicality, do you mind agreeing to assign the copyright of your contributions to me? I'll still give you credit for writing them (do you have a twitter account?), and they'll be licensed under the MIT license like everything else here.

**Comment by johnnesky** [comment]
I have one more question. I see you are tracking whether note input came from the displayed piano or from midi events. Does this solve any problem you encountered? Is there a reason why they can't be the same?

**Comment by zOadT** [comment]
Hey,

thank you very much for your feedback! I will implement it tomorrow (no idea why I havn't directly used bitwise operators 😄)

Also thanks for the clearification concerning `maintainLiveInput`. Makes sense to me, so I will leave it as it is.

Sure, I agree to assign you the copyright of these contributions. BeepBox is pretty cool so I'm glad if I can contribute to it. But could you please tell me how to actually do that? Is it enough when I add your copyright note on top of the files? My twitter account has the same name as my GitHub account.

Concerning your second post: This is just for the edge case that you remove a Midi device while playing notes from the onscreen piano or another midi device. But yeah, the complexity is probably not worth it, so I can remove it if you want me to 🙂

**Comment by zOadT** [comment]
Applied the first patch of suggestions. The `switch(true)` pattern may be a bit controversial, so I can switch to if/else if you want. But I found it pretty easier to read in this situation (I know that ` && velocity == 0` isn't necessary in the last case, but again I found that it is easier to read)

**Comment by johnnesky** [comment]
Wow, I don't think I've ever encountered the `switch(true)` pattern before! I think I can see the appeal, although I try to lean toward patterns that work in other programming languages since TypeScript isn't the only language I use regularly. I may end up changing it later but I won't force you to change it before accepting the pull request. 

As for tracking input context, I think I would prefer simplicity in this case. I don't imagine people will be disconnecting MIDI devices while clicking on the on-screen piano very often.

As for copyright... Well, I'm doing some research now, and I think the only reason why I would need to hold the copyright would be if I wanted to change the terms of the license, but I do not expect to stop using the MIT license for BeepBox. I will change the copyright notice at the top of the license text to say that the copyright belongs to the project's authors, instead of specifically to me. So I'm rescinding my request as long as you understand that your contribution will also be shared under that license. 

Thank you for bearing with me as I figure out how to be a proper open source steward, and thanks for your contribution!

**Comment by zOadT** [comment]
For the sake of all our peace of mind I just removed `switch(true)` already 😄 

Of course, I will merge master when you updated the license. But I am in no hurry to merge this PR, so feel free to take your time to sort these things out 🙂 

I really appreciate the time you invest in this PR!

Concerning Firefox: Firefox 99 is released now, but the way to get midi input working on Firefox is [a bit weird currently](https://extensionworkshop.com/documentation/publish/site-permission-add-on/#example-webmidi) (probably to prevent fingerprinting). If I understand it correctly, you have to let the user install an add-on just to be able to request the midi permission. I like to think of this feature as a nice to have optional one, so I would prefer to just keep it chome only for now, as this still seems to be pretty experimental anyway.

**Comment by johnnesky** [comment]
I've updated the license & copyright notices!

**Comment by zOadT** [comment]
Thank you very much! Main is now merged into the branch.

**Comment by johnnesky** [comment]
Your PR has been merged into main now, thanks! I've got some other stuff I wanna add to the next release but I'll let you know when I publish it! I think now would be a good time to add the ability to record live input into the song data...

**Comment by johnnesky** [comment]
Hello again @zOadT! I think I'm almost ready to publish a version of BeepBox that includes your MIDI feature as well as general recording functionality! You can try out the current version at:
https://shaktool.neocities.org/beepbox_recording/
Look in the preferences menu for the recording setup dialog.

**Comment by zOadT** [comment]
Wow, the recording feature is really cool! Looking forward to the next release! (Also I didn't know about the wicki-hayden layout, cool to learn these things through beepbox)

One small thing I notized while recording drums using pads on my midi device: When "snap recorded notes to the song's rhythm" is turned on a lot of my inputs are filtered out because they are too short (I am often times just quickly tapping on the pads) Technically the same applies to notes played using the keyboard, but there it isn't really a problem in practice.

Thanks for letting me know about the update, great work!

**Comment by johnnesky** [comment]
Good point, I think I've fixed the snap-to-rhythm thing now, thanks!

**Comment by zOadT** [comment]
Yes, works perfectly fine now 👍

**Comment by johnnesky** [comment]
Okay it's live! Thanks again for the pull request! :D

**Pull request merged**
